/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Feature: v3.5.2-pipeline-maturity, Property 10: ELF Markdown report contém todas as tabelas

import * as assert from 'assert';
import * as fc from 'fast-check';
import { buildMarkdownReport } from './elfReport';
import { ELFAnalysis, ELFSection, ELFSegment, ELFSymbol, ELFDynamic, ELFImport, ELFSecurity } from './elfParser';

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

const securityArb: fc.Arbitrary<ELFSecurity> = fc.record({
	relro: fc.constantFrom('full' as const, 'partial' as const, 'none' as const),
	stackCanary: fc.boolean(),
	nx: fc.boolean(),
	pie: fc.boolean(),
});

const sectionArb: fc.Arbitrary<ELFSection> = fc.record({
	name: fc.stringOf(fc.char(), { minLength: 1, maxLength: 20 }).map(s => '.' + s.replace(/\|/g, '')),
	type: fc.constantFrom('PROGBITS', 'SYMTAB', 'STRTAB', 'DYNAMIC', 'NOTE', 'NOBITS', 'NULL'),
	address: fc.nat({ max: 0xFFFFFFFF }).map(n => '0x' + n.toString(16)),
	offset: fc.nat({ max: 0xFFFFFF }),
	size: fc.nat({ max: 0xFFFFFF }),
	flags: fc.subarray(['ALLOC', 'WRITE', 'EXECINSTR'], { minLength: 0, maxLength: 3 }),
	entropy: fc.double({ min: 0, max: 8, noNaN: true }),
});

const segmentArb: fc.Arbitrary<ELFSegment> = fc.record({
	type: fc.constantFrom('LOAD', 'DYNAMIC', 'INTERP', 'NOTE', 'GNU_STACK', 'GNU_RELRO', 'PHDR'),
	offset: fc.nat({ max: 0xFFFFFF }),
	virtualAddress: fc.nat({ max: 0xFFFFFFFF }).map(n => '0x' + n.toString(16)),
	physicalAddress: fc.nat({ max: 0xFFFFFFFF }).map(n => '0x' + n.toString(16)),
	fileSize: fc.nat({ max: 0xFFFFFF }),
	memorySize: fc.nat({ max: 0xFFFFFF }),
	flags: fc.subarray(['READ', 'WRITE', 'EXECUTE'], { minLength: 0, maxLength: 3 }),
	alignment: fc.constantFrom(1, 4, 8, 16, 4096),
});

const symbolArb: fc.Arbitrary<ELFSymbol> = fc.record({
	name: fc.stringOf(fc.char(), { minLength: 1, maxLength: 30 }).map(s => s.replace(/\|/g, '')),
	value: fc.nat({ max: 0xFFFFFFFF }).map(n => '0x' + n.toString(16)),
	size: fc.nat({ max: 0xFFFF }),
	type: fc.constantFrom('FUNC', 'OBJECT', 'NOTYPE', 'SECTION', 'FILE'),
	binding: fc.constantFrom('LOCAL', 'GLOBAL', 'WEAK'),
	section: fc.constantFrom('.text', '.data', '.bss', '.rodata', 'UND', 'ABS'),
});

const dynamicArb: fc.Arbitrary<ELFDynamic> = fc.record({
	tag: fc.constantFrom('NEEDED', 'SONAME', 'RPATH', 'INIT', 'FINI', 'HASH', 'STRTAB', 'SYMTAB'),
	value: fc.stringOf(fc.char(), { minLength: 1, maxLength: 20 }).map(s => s.replace(/\|/g, '')),
});

const importArb: fc.Arbitrary<ELFImport> = fc.record({
	name: fc.stringOf(fc.char(), { minLength: 1, maxLength: 30 }).map(s => s.replace(/\|/g, '')),
	library: fc.stringOf(fc.char(), { minLength: 1, maxLength: 20 }).map(s => s.replace(/\|/g, '')),
});


/**
 * Arbitrary for a valid ELFAnalysis with isELF: true.
 * Arrays may be empty or populated — the report must always contain the headers.
 */
const validElfAnalysisArb: fc.Arbitrary<ELFAnalysis> = fc.record({
	fileName: fc.stringOf(fc.char(), { minLength: 1, maxLength: 30 }).map(s => s.replace(/\|/g, 'x') + '.elf'),
	filePath: fc.stringOf(fc.char(), { minLength: 1, maxLength: 50 }).map(s => '/tmp/' + s.replace(/\|/g, 'x') + '.elf'),
	fileSize: fc.nat({ max: 100_000_000 }),
	isELF: fc.constant(true),
	elfClass: fc.constantFrom('ELF32' as const, 'ELF64' as const),
	endianness: fc.constantFrom('little' as const, 'big' as const),
	osABI: fc.constantFrom('System V', 'Linux', 'FreeBSD', 'GNU'),
	type: fc.constantFrom('EXEC', 'DYN', 'REL', 'CORE'),
	machine: fc.constantFrom('x86_64', 'x86', 'ARM', 'AArch64', 'MIPS'),
	entryPoint: fc.nat({ max: 0xFFFFFFFF }).map(n => '0x' + n.toString(16)),
	sections: fc.array(sectionArb, { minLength: 0, maxLength: 5 }),
	segments: fc.array(segmentArb, { minLength: 0, maxLength: 5 }),
	symbols: fc.array(symbolArb, { minLength: 0, maxLength: 5 }),
	dynamicEntries: fc.array(dynamicArb, { minLength: 0, maxLength: 5 }),
	imports: fc.array(importArb, { minLength: 0, maxLength: 5 }),
	security: securityArb,
});

// ---------------------------------------------------------------------------
// Property Test
// ---------------------------------------------------------------------------

suite('Property 10: ELF Markdown report contém todas as tabelas', () => {

	/**
	 * **Validates: Requirements 4.8**
	 *
	 * For any ELFAnalysis with isELF: true, the Markdown generated by
	 * buildMarkdownReport MUST contain headers for sections, segments,
	 * symbols, and security mitigations.
	 */
	test('report contains all required section headers', () => {
		fc.assert(
			fc.property(
				validElfAnalysisArb,
				(analysis) => {
					const md = buildMarkdownReport(analysis);

					assert.ok(md.includes('## Sections'),
						'Markdown must contain "## Sections" header');
					assert.ok(md.includes('## Segments'),
						'Markdown must contain "## Segments" header');
					assert.ok(md.includes('## Symbols'),
						'Markdown must contain "## Symbols" header');
					assert.ok(md.includes('## Security Mitigations'),
						'Markdown must contain "## Security Mitigations" header');
				}
			),
			{ numRuns: 100 }
		);
	});
});


// Feature: v3.5.2-pipeline-maturity, Property 11: ELF Analysis JSON round-trip

suite('Property 11: ELF Analysis JSON round-trip', () => {

	/**
	 * **Validates: Requirements 4.9**
	 *
	 * For any valid ELFAnalysis object, JSON.parse(JSON.stringify(analysis))
	 * MUST produce an object with the same values for all fields.
	 */
	test('JSON round-trip preserves all fields', () => {
		fc.assert(
			fc.property(
				validElfAnalysisArb,
				(analysis) => {
					const roundTripped = JSON.parse(JSON.stringify(analysis));
					assert.deepStrictEqual(roundTripped, analysis);
				}
			),
			{ numRuns: 100 }
		);
	});
});
