/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import type { XorResult } from './xorScanner';
import type { MultiByteXorResult } from './multiByteXor';
import type { StackString } from './stackStringDetector';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExtractedString {
	value: string;
	offset: number;
	encoding: 'ascii' | 'unicode';
}

export interface StringsReportOptions {
	asciiStrings: ExtractedString[];
	unicodeStrings: ExtractedString[];
	xorResults: {
		singleByte: XorResult[];
		multiByte: MultiByteXorResult[];
		rolling: XorResult[];
		increment: XorResult[];
	};
	stackStrings: StackString[];
	categories: CategorizedStrings;
}

export interface CategorizedStrings {
	urls: string[];
	ips: string[];
	filePaths: string[];
	registryKeys: string[];
	emails: string[];
	other: string[];
}

// ---------------------------------------------------------------------------
// Categorization Patterns
// ---------------------------------------------------------------------------

const URL_REGEX = /^https?:\/\/.+/i;
const IP_REGEX = /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$/;
const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
const FILE_PATH_REGEX = /^[a-zA-Z]:\\|^\\\\|^\/[a-zA-Z]/;
const REGISTRY_KEY_REGEX = /^HKEY_|^HKLM\\|^HKCU\\|^HKCR\\|^HKU\\|^HKCC\\/i;

// ---------------------------------------------------------------------------
// Category Icons
// ---------------------------------------------------------------------------

const CATEGORY_ICONS: Record<keyof CategorizedStrings, string> = {
	urls: '🌐',
	ips: '📡',
	filePaths: '📁',
	registryKeys: '🔑',
	emails: '📧',
	other: '📝',
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Categorize an array of strings into known categories using regex patterns.
 * Strings that don't match any pattern are placed in the "other" category.
 */
export function categorizeStrings(strings: string[]): CategorizedStrings {
	const result: CategorizedStrings = {
		urls: [],
		ips: [],
		filePaths: [],
		registryKeys: [],
		emails: [],
		other: [],
	};

	for (const str of strings) {
		if (URL_REGEX.test(str)) {
			result.urls.push(str);
		} else if (IP_REGEX.test(str)) {
			result.ips.push(str);
		} else if (EMAIL_REGEX.test(str)) {
			result.emails.push(str);
		} else if (REGISTRY_KEY_REGEX.test(str)) {
			result.registryKeys.push(str);
		} else if (FILE_PATH_REGEX.test(str)) {
			result.filePaths.push(str);
		} else {
			result.other.push(str);
		}
	}

	return result;
}

/**
 * Generate a comprehensive Markdown report for extracted strings,
 * including XOR deobfuscation results, stack strings, and categorization.
 */
export function generateStringsReport(options: StringsReportOptions): string {
	const lines: string[] = [];

	// --- Header ---
	lines.push('# HexCore Strings Extractor Report');
	lines.push('');

	// --- Summary ---
	appendSummary(lines, options);

	// --- ASCII Strings ---
	appendExtractedStrings(lines, 'ASCII Strings', options.asciiStrings);

	// --- Unicode Strings ---
	appendExtractedStrings(lines, 'Unicode Strings', options.unicodeStrings);

	// --- XOR Single-byte ---
	appendXorSingleByte(lines, options.xorResults.singleByte);

	// --- XOR Multi-byte ---
	appendXorMultiByte(lines, options.xorResults.multiByte);

	// --- XOR Rolling ---
	appendXorRolling(lines, options.xorResults.rolling);

	// --- XOR Increment ---
	appendXorIncrement(lines, options.xorResults.increment);

	// --- Stack Strings ---
	appendStackStrings(lines, options.stackStrings);

	// --- Categorization ---
	appendCategorization(lines, options.categories);

	// --- Footer ---
	lines.push('---');
	lines.push('*Generated by HexCore Strings Extractor v1.3.0*');
	lines.push('');

	return lines.join('\n');
}


// ---------------------------------------------------------------------------
// Summary Section
// ---------------------------------------------------------------------------

function appendSummary(lines: string[], options: StringsReportOptions): void {
	const totalAscii = options.asciiStrings.length;
	const totalUnicode = options.unicodeStrings.length;
	const totalXorSingle = options.xorResults.singleByte.length;
	const totalXorMulti = options.xorResults.multiByte.length;
	const totalXorRolling = options.xorResults.rolling.length;
	const totalXorIncrement = options.xorResults.increment.length;
	const totalStack = options.stackStrings.length;
	const totalXor = totalXorSingle + totalXorMulti + totalXorRolling + totalXorIncrement;
	const grandTotal = totalAscii + totalUnicode + totalXor + totalStack;

	lines.push('## Summary');
	lines.push('');
	lines.push('| Category | Count | Risk |');
	lines.push('|----------|-------|------|');
	lines.push(`| **ASCII Strings** | ${totalAscii} | — |`);
	lines.push(`| **Unicode Strings** | ${totalUnicode} | — |`);
	lines.push(`| **XOR Single-byte** | ${totalXorSingle} | ${riskBadge(totalXorSingle)} |`);
	lines.push(`| **XOR Multi-byte** | ${totalXorMulti} | ${riskBadge(totalXorMulti)} |`);
	lines.push(`| **XOR Rolling** | ${totalXorRolling} | ${riskBadge(totalXorRolling)} |`);
	lines.push(`| **XOR Increment** | ${totalXorIncrement} | ${riskBadge(totalXorIncrement)} |`);
	lines.push(`| **Stack Strings** | ${totalStack} | ${riskBadge(totalStack)} |`);
	lines.push(`| **Total** | **${grandTotal}** | |`);
	lines.push('');
}

// ---------------------------------------------------------------------------
// ASCII / Unicode Strings Section
// ---------------------------------------------------------------------------

function appendExtractedStrings(lines: string[], title: string, strings: ExtractedString[]): void {
	if (strings.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## ${title} (${strings.length})`);
	lines.push('');
	lines.push('| # | Offset | Value |');
	lines.push('|---|--------|-------|');

	const displayMax = 100;
	const sliced = strings.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const s = sliced[i];
		const offsetHex = formatOffset(s.offset);
		const escaped = escapeMarkdown(s.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${offsetHex} | \`${escaped}\` |`);
	}

	if (strings.length > displayMax) {
		lines.push(`| ... | — | *${strings.length - displayMax} more* |`);
	}
	lines.push('');
}

// ---------------------------------------------------------------------------
// XOR Single-byte Section
// ---------------------------------------------------------------------------

function appendXorSingleByte(lines: string[], results: XorResult[]): void {
	if (results.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## 🔓 XOR Single-byte Strings (${results.length})`);
	lines.push('');
	lines.push('| # | Key | Offset | Confidence | Decoded Value |');
	lines.push('|---|-----|--------|------------|---------------|');

	const displayMax = 100;
	const sliced = results.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const r = sliced[i];
		const keyHex = `0x${r.key.toString(16).toUpperCase().padStart(2, '0')}`;
		const offsetHex = formatOffset(r.offset);
		const conf = `${(r.confidence * 100).toFixed(1)}%`;
		const escaped = escapeMarkdown(r.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${keyHex} | ${offsetHex} | ${conf} | \`${escaped}\` |`);
	}

	if (results.length > displayMax) {
		lines.push(`| ... | — | — | — | *${results.length - displayMax} more* |`);
	}
	lines.push('');
}


// ---------------------------------------------------------------------------
// XOR Multi-byte Section
// ---------------------------------------------------------------------------

function appendXorMultiByte(lines: string[], results: MultiByteXorResult[]): void {
	if (results.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## 🔓 XOR Multi-byte Strings (${results.length})`);
	lines.push('');
	lines.push('| # | Key | Key Size | Offset | Confidence | Decoded Value |');
	lines.push('|---|-----|----------|--------|------------|---------------|');

	const displayMax = 100;
	const sliced = results.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const r = sliced[i];
		const offsetHex = formatOffset(r.offset);
		const conf = `${(r.confidence * 100).toFixed(1)}%`;
		const escaped = escapeMarkdown(r.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${r.keyHex} | ${r.keySize}B | ${offsetHex} | ${conf} | \`${escaped}\` |`);
	}

	if (results.length > displayMax) {
		lines.push(`| ... | — | — | — | — | *${results.length - displayMax} more* |`);
	}
	lines.push('');
}

// ---------------------------------------------------------------------------
// XOR Rolling Section
// ---------------------------------------------------------------------------

function appendXorRolling(lines: string[], results: XorResult[]): void {
	if (results.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## 🔓 XOR Rolling Strings (${results.length})`);
	lines.push('');
	lines.push('| # | Seed | Offset | Confidence | Decoded Value |');
	lines.push('|---|------|--------|------------|---------------|');

	const displayMax = 100;
	const sliced = results.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const r = sliced[i];
		const seedHex = `0x${r.key.toString(16).toUpperCase().padStart(2, '0')}`;
		const offsetHex = formatOffset(r.offset);
		const conf = `${(r.confidence * 100).toFixed(1)}%`;
		const escaped = escapeMarkdown(r.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${seedHex} | ${offsetHex} | ${conf} | \`${escaped}\` |`);
	}

	if (results.length > displayMax) {
		lines.push(`| ... | — | — | — | *${results.length - displayMax} more* |`);
	}
	lines.push('');
}

// ---------------------------------------------------------------------------
// XOR Increment Section
// ---------------------------------------------------------------------------

function appendXorIncrement(lines: string[], results: XorResult[]): void {
	if (results.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## 🔓 XOR Increment Strings (${results.length})`);
	lines.push('');
	lines.push('| # | Base Key | Offset | Confidence | Decoded Value |');
	lines.push('|---|----------|--------|------------|---------------|');

	const displayMax = 100;
	const sliced = results.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const r = sliced[i];
		const keyHex = `0x${r.key.toString(16).toUpperCase().padStart(2, '0')}`;
		const offsetHex = formatOffset(r.offset);
		const conf = `${(r.confidence * 100).toFixed(1)}%`;
		const escaped = escapeMarkdown(r.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${keyHex} | ${offsetHex} | ${conf} | \`${escaped}\` |`);
	}

	if (results.length > displayMax) {
		lines.push(`| ... | — | — | — | *${results.length - displayMax} more* |`);
	}
	lines.push('');
}

// ---------------------------------------------------------------------------
// Stack Strings Section
// ---------------------------------------------------------------------------

function appendStackStrings(lines: string[], results: StackString[]): void {
	if (results.length === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push(`## 🧱 Stack Strings (${results.length})`);
	lines.push('');
	lines.push('| # | Offset | Instructions | Addressing | Value |');
	lines.push('|---|--------|--------------|------------|-------|');

	const displayMax = 100;
	const sliced = results.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const s = sliced[i];
		const offsetHex = formatOffset(s.offset);
		const escaped = escapeMarkdown(s.value).substring(0, 80);
		lines.push(`| ${i + 1} | ${offsetHex} | ${s.instructionCount} | ${s.addressingMode} | \`${escaped}\` |`);
	}

	if (results.length > displayMax) {
		lines.push(`| ... | — | — | — | *${results.length - displayMax} more* |`);
	}
	lines.push('');
}


// ---------------------------------------------------------------------------
// Categorization Section
// ---------------------------------------------------------------------------

function appendCategorization(lines: string[], categories: CategorizedStrings): void {
	const totalCategorized = categories.urls.length + categories.ips.length
		+ categories.filePaths.length + categories.registryKeys.length
		+ categories.emails.length;

	if (totalCategorized === 0) {
		return;
	}

	lines.push('---');
	lines.push('');
	lines.push('## Categorized Strings');
	lines.push('');

	appendCategoryTable(lines, 'urls', 'URLs', categories.urls);
	appendCategoryTable(lines, 'ips', 'IP Addresses', categories.ips);
	appendCategoryTable(lines, 'filePaths', 'File Paths', categories.filePaths);
	appendCategoryTable(lines, 'registryKeys', 'Registry Keys', categories.registryKeys);
	appendCategoryTable(lines, 'emails', 'Email Addresses', categories.emails);
}

function appendCategoryTable(
	lines: string[],
	key: keyof CategorizedStrings,
	label: string,
	items: string[],
): void {
	if (items.length === 0) {
		return;
	}

	const icon = CATEGORY_ICONS[key];
	lines.push(`### ${icon} ${label} (${items.length})`);
	lines.push('');
	lines.push('| # | Value |');
	lines.push('|---|-------|');

	const displayMax = 50;
	const sliced = items.slice(0, displayMax);
	for (let i = 0; i < sliced.length; i++) {
		const escaped = escapeMarkdown(sliced[i]).substring(0, 100);
		lines.push(`| ${i + 1} | \`${escaped}\` |`);
	}

	if (items.length > displayMax) {
		lines.push(`| ... | *${items.length - displayMax} more* |`);
	}
	lines.push('');
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function riskBadge(count: number): string {
	if (count === 0) {
		return '🟢 None';
	}
	if (count <= 5) {
		return '🟡 Low';
	}
	return '🔴 High';
}

function formatOffset(offset: number): string {
	return `0x${offset.toString(16).toUpperCase().padStart(8, '0')}`;
}

function escapeMarkdown(text: string): string {
	return text
		.replace(/\|/g, '\\|')
		.replace(/\n/g, ' ')
		.replace(/\r/g, '');
}
