/*---------------------------------------------------------------------------------------------
 *  HexCore Entropy Analyzer v1.1.0
 *  Markdown report generation
 *  Copyright (c) HikariSystem. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import { EntropyAnalysisResult, EntropyBlock } from './types';

/**
 * Optional section mapping for correlating entropy blocks with binary sections.
 */
export interface SectionInfo {
	name: string;
	offset: number;
	size: number;
}

/**
 * Finds the section name that contains the given block offset.
 * Returns undefined if no section matches or sections are not provided.
 */
export function findSectionForBlock(blockOffset: number, sections?: SectionInfo[]): string | undefined {
	if (!sections || sections.length === 0) {
		return undefined;
	}
	for (const sec of sections) {
		if (blockOffset >= sec.offset && blockOffset < sec.offset + sec.size) {
			return sec.name;
		}
	}
	return undefined;
}

export function generateEntropyReport(result: EntropyAnalysisResult, sections?: SectionInfo[]): string {
	const highEntropyPercentage = result.totalBlocks > 0
		? ((result.summary.highEntropyBlocks.length / result.totalBlocks) * 100).toFixed(1)
		: '0.0';
	const lowEntropyPercentage = result.totalBlocks > 0
		? ((result.summary.lowEntropyBlocks.length / result.totalBlocks) * 100).toFixed(1)
		: '0.0';

	let report = `# HexCore Entropy Analysis Report

## File Information

| Property | Value |
|----------|-------|
| **File Name** | ${result.fileName} |
| **File Path** | ${result.filePath} |
| **File Size** | ${formatBytes(result.fileSize)} |
| **Block Size** | ${result.blockSize} bytes |
| **Total Blocks** | ${result.totalBlocks} |

---

## Entropy Statistics

| Metric | Value |
|--------|-------|
| **Average Entropy** | ${result.summary.averageEntropy.toFixed(4)} / 8.00 |
| **Maximum Entropy** | ${result.summary.maxEntropy.toFixed(4)} |
| **Minimum Entropy** | ${result.summary.minEntropy.toFixed(4)} |
| **High Entropy Blocks (>7.0)** | ${result.summary.highEntropyBlocks.length} (${highEntropyPercentage}%) |
| **Low Entropy Blocks (<1.0)** | ${result.summary.lowEntropyBlocks.length} (${lowEntropyPercentage}%) |

---

## Assessment

**${result.summary.assessment}**

${result.summary.assessmentDetails}

---

## Entropy Graph

\`\`\`
${result.graph}
\`\`\`

**Legend:** Each column represents a block. Height shows entropy (0-8).
- Low entropy (0-3): Likely plaintext, null bytes, or repetitive data
- Medium entropy (3-6): Code, structured data
- High entropy (6-8): Encrypted, compressed, or random data

---

## Crypto Signals (Experimental)

`;

	if (result.cryptoSignals.length === 0) {
		report += '*No cryptographic signals flagged by current heuristics.*\n';
	} else {
		report += '| Type | Confidence | Offset | Details |\n';
		report += '|------|------------|--------|---------|\n';
		for (const signal of result.cryptoSignals) {
			const offset = typeof signal.offset === 'number'
				? `0x${signal.offset.toString(16).toUpperCase()}`
				: '-';
			report += `| ${signal.type} | ${(signal.confidence * 100).toFixed(1)}% | ${offset} | ${signal.details} |\n`;
		}
	}

	report += `

---

## High Entropy Regions (>7.0)

`;

	if (result.summary.highEntropyBlocks.length > 0) {
		const hasSections = sections && sections.length > 0;
		if (hasSections) {
			report += '| Offset | Entropy | Status | Section |\n';
			report += '|--------|---------|--------|---------|\n';
		} else {
			report += '| Offset | Entropy | Status |\n';
			report += '|--------|---------|--------|\n';
		}
		for (const block of result.summary.highEntropyBlocks.slice(0, 20)) {
			const offsetStr = `0x${block.offset.toString(16).toUpperCase().padStart(8, '0')}`;
			const entropyStr = block.entropy.toFixed(4);
			const statusLabel = block.entropy > 7.0 ? '⚠️ ALTA ENTROPIA' : '';
			if (hasSections) {
				const sectionName = findSectionForBlock(block.offset, sections) || '-';
				report += `| ${offsetStr} | ${entropyStr} | ${statusLabel} | ${sectionName} |\n`;
			} else {
				report += `| ${offsetStr} | ${entropyStr} | ${statusLabel} |\n`;
			}
		}
		if (result.summary.highEntropyBlocks.length > 20) {
			if (hasSections) {
				report += `| ... | ... | *${result.summary.highEntropyBlocks.length - 20} more regions* | ... |\n`;
			} else {
				report += `| ... | ... | *${result.summary.highEntropyBlocks.length - 20} more regions* |\n`;
			}
		}
	} else {
		report += '*No high entropy regions detected.*\n';
	}

	report += `
---

## Entropy Scale Reference

| Range | Typical Content |
|-------|-----------------|
| 0.0 - 1.0 | Null bytes, single repeated byte |
| 1.0 - 3.0 | Simple text, repetitive patterns |
| 3.0 - 5.0 | English text, source code |
| 5.0 - 6.5 | Compiled code, mixed content |
| 6.5 - 7.5 | Compressed data (ZIP, PNG) |
| 7.5 - 8.0 | Encrypted or random data |

---
*Generated by HexCore Entropy Analyzer v1.1.0*
`;

	return report;
}

function formatBytes(bytes: number): string {
	if (bytes === 0) {
		return '0 B';
	}
	const k = 1024;
	const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}
